#!/bin/bash
# file name preinst
# Pre-install script for runn. This removes old versions runn gtc.

echo "Looking for old versions of runn ..."

if [ -f "/usr/bin/runn" ];then
    sudo rm -f /usr/bin/runn
    echo "Removed old runn from /usr/bin ..."
fi

if [ -d "/usr/share/runn" ];then
    sudo rm -rf /usr/share/runn
    echo "Removed old runn from /usr/share ..."
fi
